# Generated by Django 5.0.7 on 2024-07-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_invoice_order_report_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='phone_suppliers',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
