# Generated by Django 5.0.7 on 2024-07-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_customers_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='phone_suppliers',
            field=models.CharField(max_length=100),
        ),
    ]
